# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addContact.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(189, 221)
        self.roadname_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.roadname_lineEdit.setGeometry(QtCore.QRect(60, 50, 113, 21))
        self.roadname_lineEdit.setObjectName("roadname_lineEdit")
        self.postcode_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.postcode_lineEdit.setGeometry(QtCore.QRect(60, 140, 113, 21))
        self.postcode_lineEdit.setObjectName("postcode_lineEdit")
        self.house_name_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.house_name_lineEdit.setGeometry(QtCore.QRect(82, 20, 91, 21))
        self.house_name_lineEdit.setObjectName("house_name_lineEdit")
        self.save_contact_Button = QtWidgets.QPushButton(Dialog)
        self.save_contact_Button.setGeometry(QtCore.QRect(10, 180, 80, 21))
        self.save_contact_Button.setObjectName("save_contact_Button")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(16, 20, 61, 21))
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 110, 41, 21))
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 80, 41, 21))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 31, 21))
        self.label_3.setObjectName("label_3")
        self.county_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.county_lineEdit.setGeometry(QtCore.QRect(60, 110, 113, 21))
        self.county_lineEdit.setObjectName("county_lineEdit")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 140, 51, 21))
        self.label_6.setObjectName("label_6")
        self.areaname_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.areaname_lineEdit.setGeometry(QtCore.QRect(60, 80, 113, 21))
        self.areaname_lineEdit.setObjectName("areaname_lineEdit")
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setGeometry(QtCore.QRect(90, 180, 80, 21))
        self.cancelButton.setObjectName("cancelButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.house_name_lineEdit, self.roadname_lineEdit)
        Dialog.setTabOrder(self.roadname_lineEdit, self.areaname_lineEdit)
        Dialog.setTabOrder(self.areaname_lineEdit, self.county_lineEdit)
        Dialog.setTabOrder(self.county_lineEdit, self.postcode_lineEdit)
        Dialog.setTabOrder(self.postcode_lineEdit, self.save_contact_Button)
        Dialog.setTabOrder(self.save_contact_Button, self.cancelButton)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add Contact"))
        self.save_contact_Button.setText(_translate("Dialog", "Save Contact"))
        self.label.setText(_translate("Dialog", "House Name"))
        self.label_5.setText(_translate("Dialog", "County"))
        self.label_4.setText(_translate("Dialog", "Area"))
        self.label_3.setText(_translate("Dialog", "Road"))
        self.label_6.setText(_translate("Dialog", " Postcode"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
