# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addUserData.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(208, 260)
        self.settingSave_Button = QtWidgets.QPushButton(Dialog)
        self.settingSave_Button.setGeometry(QtCore.QRect(20, 230, 91, 21))
        self.settingSave_Button.setObjectName("settingSave_Button")
        self.settingUserName_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.settingUserName_lineEdit.setGeometry(QtCore.QRect(80, 10, 113, 21))
        self.settingUserName_lineEdit.setObjectName("settingUserName_lineEdit")
        self.label_24 = QtWidgets.QLabel(Dialog)
        self.label_24.setGeometry(QtCore.QRect(30, 130, 47, 13))
        self.label_24.setObjectName("label_24")
        self.settingUserEmail_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.settingUserEmail_lineEdit.setGeometry(QtCore.QRect(80, 200, 113, 21))
        self.settingUserEmail_lineEdit.setObjectName("settingUserEmail_lineEdit")
        self.settingUserCounty_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.settingUserCounty_lineEdit.setGeometry(QtCore.QRect(80, 130, 113, 21))
        self.settingUserCounty_lineEdit.setObjectName("settingUserCounty_lineEdit")
        self.settingUserArea_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.settingUserArea_lineEdit.setGeometry(QtCore.QRect(80, 100, 113, 21))
        self.settingUserArea_lineEdit.setObjectName("settingUserArea_lineEdit")
        self.settingUserRoad_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.settingUserRoad_lineEdit.setGeometry(QtCore.QRect(80, 70, 113, 21))
        self.settingUserRoad_lineEdit.setObjectName("settingUserRoad_lineEdit")
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(6, 70, 71, 20))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(Dialog)
        self.label_23.setGeometry(QtCore.QRect(40, 100, 41, 20))
        self.label_23.setObjectName("label_23")
        self.settingUserHouse_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.settingUserHouse_lineEdit.setGeometry(QtCore.QRect(80, 40, 113, 21))
        self.settingUserHouse_lineEdit.setText("")
        self.settingUserHouse_lineEdit.setObjectName("settingUserHouse_lineEdit")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 71, 20))
        self.label_3.setObjectName("label_3")
        self.settingUserPostcode_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.settingUserPostcode_lineEdit.setGeometry(QtCore.QRect(80, 160, 113, 21))
        self.settingUserPostcode_lineEdit.setObjectName("settingUserPostcode_lineEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 61, 16))
        self.label.setObjectName("label")
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(20, 200, 51, 20))
        self.label_20.setObjectName("label_20")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 160, 51, 21))
        self.label_4.setObjectName("label_4")
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setGeometry(QtCore.QRect(120, 230, 80, 21))
        self.cancelButton.setObjectName("cancelButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add User"))
        self.settingSave_Button.setText(_translate("Dialog", "Update Settings"))
        self.label_24.setText(_translate("Dialog", "County :"))
        self.label_22.setText(_translate("Dialog", "Road Name  :"))
        self.label_23.setText(_translate("Dialog", "Area  :"))
        self.label_3.setText(_translate("Dialog", "Your House:"))
        self.label.setText(_translate("Dialog", "Your Name:"))
        self.label_20.setText(_translate("Dialog", "Your Email:"))
        self.label_4.setText(_translate("Dialog", "Postcode:"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
