# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'generateInvoice.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(240, 300)
        self.from_comboBox = QtWidgets.QComboBox(Dialog)
        self.from_comboBox.setGeometry(QtCore.QRect(60, 10, 72, 22))
        self.from_comboBox.setObjectName("from_comboBox")
        self.billTo_comboBox = QtWidgets.QComboBox(Dialog)
        self.billTo_comboBox.setGeometry(QtCore.QRect(60, 40, 72, 22))
        self.billTo_comboBox.setObjectName("billTo_comboBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 47, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 47, 20))
        self.label_2.setObjectName("label_2")
        self.genInvoice_tableView = QtWidgets.QTableView(Dialog)
        self.genInvoice_tableView.setGeometry(QtCore.QRect(10, 70, 221, 192))
        self.genInvoice_tableView.setObjectName("genInvoice_tableView")
        self.invoiceNo_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.invoiceNo_lineEdit.setGeometry(QtCore.QRect(200, 10, 31, 21))
        self.invoiceNo_lineEdit.setObjectName("invoiceNo_lineEdit")
        self.weekNo_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.weekNo_lineEdit.setGeometry(QtCore.QRect(200, 40, 31, 21))
        self.weekNo_lineEdit.setObjectName("weekNo_lineEdit")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(140, 10, 61, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(150, 40, 47, 21))
        self.label_4.setObjectName("label_4")
        self.generateButton = QtWidgets.QPushButton(Dialog)
        self.generateButton.setGeometry(QtCore.QRect(10, 270, 80, 21))
        self.generateButton.setObjectName("generateButton")
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setGeometry(QtCore.QRect(150, 270, 80, 21))
        self.cancelButton.setObjectName("cancelButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Generate Invoice"))
        self.label.setText(_translate("Dialog", "From:"))
        self.label_2.setText(_translate("Dialog", "Bill To:"))
        self.label_3.setText(_translate("Dialog", "Invoice No."))
        self.label_4.setText(_translate("Dialog", "Week No."))
        self.generateButton.setText(_translate("Dialog", "Generate"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
