# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'workDay.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(212, 266)
        Dialog.setToolTip("")
        self.dayRate_SpinBox = QtWidgets.QDoubleSpinBox(Dialog)
        self.dayRate_SpinBox.setGeometry(QtCore.QRect(140, 35, 62, 22))
        self.dayRate_SpinBox.setMaximum(999.99)
        self.dayRate_SpinBox.setSingleStep(10.0)
        self.dayRate_SpinBox.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.dayRate_SpinBox.setObjectName("dayRate_SpinBox")
        self.dateEdit = QtWidgets.QDateEdit(Dialog)
        self.dateEdit.setGeometry(QtCore.QRect(92, 10, 110, 22))
        self.dateEdit.setReadOnly(True)
        self.dateEdit.setObjectName("dateEdit")
        self.extras_checkBox = QtWidgets.QCheckBox(Dialog)
        self.extras_checkBox.setGeometry(QtCore.QRect(10, 35, 72, 19))
        self.extras_checkBox.setObjectName("extras_checkBox")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 80, 191, 151))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.notes_textEdit = QtWidgets.QTextEdit(self.tab)
        self.notes_textEdit.setGeometry(QtCore.QRect(-2, -1, 191, 127))
        self.notes_textEdit.setObjectName("notes_textEdit")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.extras_textEdit = QtWidgets.QTextEdit(self.tab_2)
        self.extras_textEdit.setGeometry(QtCore.QRect(-2, -1, 191, 127))
        self.extras_textEdit.setObjectName("extras_textEdit")
        self.tabWidget.addTab(self.tab_2, "")
        self.ok_Button = QtWidgets.QPushButton(Dialog)
        self.ok_Button.setGeometry(QtCore.QRect(20, 240, 80, 21))
        self.ok_Button.setObjectName("ok_Button")
        self.cancel_Button = QtWidgets.QPushButton(Dialog)
        self.cancel_Button.setGeometry(QtCore.QRect(110, 240, 80, 21))
        self.cancel_Button.setObjectName("cancel_Button")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(80, 35, 61, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 71, 20))
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(130, 60, 72, 22))
        self.comboBox.setObjectName("comboBox")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(90, 60, 31, 16))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "New Entry"))
        self.extras_checkBox.setText(_translate("Dialog", "Extras"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Notes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Extras"))
        self.ok_Button.setText(_translate("Dialog", "Ok"))
        self.cancel_Button.setText(_translate("Dialog", "Cancel"))
        self.label.setText(_translate("Dialog", "Day Rate £"))
        self.label_2.setText(_translate("Dialog", "Date Selected"))
        self.label_3.setText(_translate("Dialog", "Clients"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
